---
version: "3.8"

networks:
  backend:

services:
  database:
    image: postgres
    container_name: chroma_core_telemetric_database
    environment:

      POSTGRES_USER: "client"
      POSTGRES_PASSWORD: "L5LevyxEaFsP3p9TGnPddrY4RcZUHLQ3q8rEwL8K2bddBNzS9Q2TY697EWyX4VTB45HL7bkgpcxzTYnVU2v3HAfJTphMni2AYKVp5BtYUmuGgymK86fz2tYuYs9YSLNh"
      POSTGRES_DB: "telemetry"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/posgresql
    ports:
      - 5432:5432
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready" ,"-d", "telemetry"]
      timeout: 2s
      retries: 240
      start_period: 10s
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: chroma_core_telemetric_server
    environment:
      DBUSER: "client"
      DBPASS: "L5LevyxEaFsP3p9TGnPddrY4RcZUHLQ3q8rEwL8K2bddBNzS9Q2TY697EWyX4VTB45HL7bkgpcxzTYnVU2v3HAfJTphMni2AYKVp5BtYUmuGgymK86fz2tYuYs9YSLNh"
      DBHOST: "database:5432"
      DBNAME: "telemetry"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
    ports:
      - 1234:1234
    restart: unless-stopped