---
version: "3.8"

networks:
  backend:

services:
  database:
    image: postgres
    container_name: chroma_core_telemetric_database
    environment:

      POSTGRES_USER: "client"
      POSTGRES_PASSWORD: "L5LevyxEaFsP3p9TGnPddrY4RcZUHLQ3q8rEwL8K2bddBNzS9Q2TY697EWyX4VTB45HL7bkgpcxzTYnVU2v3HAfJTphMni2AYKVp5BtYUmuGgymK86fz2tYuYs9YSLNh"
      POSTGRES_DB: "telemetry"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/posgresql
    ports:
      - 5432:5432
    networks:
      - backend
    restart: unless-stopped



    # environment:
    #   - MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    #   - MYSQL_DATABASE: "telemetry"
      #- MYSQL_ROOT_PASSWORD: "L5LevyxEaFsP3p9TGnPddrY4RcZUHLQ3q8rEwL8K2bddBNzS9Q2TY697EWyX4VTB45HL7bkgpcxzTYnVU2v3HAfJTphMni2AYKVp5BtYUmuGgymK86fz2tYuYs9YSLNh"