CREATE TABLE ragequits (
	id			SERIAL PRIMARY KEY NOT NULL,
	level		INT NOT NULL,
	time		DECIMAL NOT NULL,
	positionx	DECIMAL NOT NULL,
	positiony	DECIMAL NOT NULL
);

CREATE TABLE wins (
	id			SERIAL PRIMARY KEY NOT NULL,
	level		INT NOT NULL,
	time		DECIMAL NOT NULL
);

CREATE TABLE deaths (
	id			SERIAL PRIMARY KEY NOT NULL,
	level		INT NOT NULL,
	time		DECIMAL NOT NULL,
	positionx	DECIMAL NOT NULL,
	positiony	DECIMAL NOT NULL
);